
project_id = "rmvrrrqlqrmtiiwxugfe"

[functions]
[functions.generate-backup]
verify_jwt = true

[[auth.redirect_urls]]
url = "http://localhost:5173/auth/callback"

[[storage.buckets]]
name = "client-photos"
public = true
