// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmvrrrqlqrmtiiwxugfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtdnJycnFscXJtdGlpd3h1Z2ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjA1MTQsImV4cCI6MjA2MTA5NjUxNH0.RXHa13XSoVfOWGVMivdGMWxdGntjL_NAVxr-kxNP6Cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);